twig:
  default_path: "%kernel.project_dir%/templates"
  paths:
    "%kernel.project_dir%/assets/images/icons": icons

when@test:
  twig:
    strict_variables: true
    form_themes: ["tailwind_2_layout.html.twig"]
